CERTIFICATE_DIRECTORY_ROOT ?= vendor/parasite-signatures
CERTIFICATE_COMMON := $(CERTIFICATE_DIRECTORY_ROOT)/common

ifeq ($(TARGET_BUILD_FULLY_SIGN),true)
TARGET_DEFAULT_DEV_SIGN := true
TARGET_DEFAULT_CERTIFICATE_OVERRIDE := true
endif

ifeq ($(TARGET_DEFAULT_CERTIFICATE_OVERRIDE),true)
$(call inherit-product, $(CERTIFICATE_COMMON)/certificates.mk)
endif

ifeq ($(TARGET_DEFAULT_DEV_SIGN),true)
PRODUCT_DEFAULT_DEV_CERTIFICATE := $(CERTIFICATE_COMMON)/data/releasekey
PRODUCT_EXTRA_RECOVERY_KEYS :=
endif
