#!/bin/bash
#
# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generates a public/private key pair suitable for use in signing
# android .apks and OTA update packages.

if [ "$#" -lt 2 -o "$#" -gt 3 ]; then
	cat <<EOF
Usage: $0 <name> <subject> [<bit>]

Creates <name>.pk8 key and <name>.x509.pem cert.  Cert contains the
given <subject>. Use given <bit> if set.
EOF
	exit 2
fi

if [[ -e $1.pk8 || -e $1.x509.pem ]]; then
	echo "$1.pk8 and/or $1.x509.pem already exist; please delete them first"
	echo "if you want to replace them."
	exit 1
fi

if ! [[ $3 =~ ^[0-9]+$ ]]; then
	bit=2048
else
	bit=$3
fi

openssl genrsa -out $1-private.pem -f4 $bit
hash="-sha256"

openssl req -new -x509 ${hash} -key $1-private.pem -out $1.x509.pem \
	-days 10000 -subj "$2" &

echo "creating ${1}.pk8 with no password"
openssl pkcs8 -in $1-private.pem -topk8 -outform DER -out $1.pk8 -nocrypt 2>/dev/null

wait
wait
